show databases;
use atividade3uc03;
show create table medicos;
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-01-10','14:00',110.00,10,12,1);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-02-10','11:00',120.00,10,13,2);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-03-10','10:00',120.00,10,14,3);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-04-10','14:00',120.00,10,15,4);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-05-10','09:00',110.00,10,16,5);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-06-10','10:00',120.00,10,17,5);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-07-10','11:00',120.00,10,18,3);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-08-10','08;38',120.00,10,19,2);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-09-10','17:00',110.00,10,20,1);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-10-10','16:00',120.00,10,21,3);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-11-10','13:00',120.00,10,22,2);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-12-10','17:15',110.00,10,23,5);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-01-11','11:00',120.00,10,12,1);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-02-11','14:15',120.00,10,12,2);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-03-11','13:00',110.00,10,12,1);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-04-11','14:00',120.00,10,12,4);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-05-11','09:15',120.00,10,20,1);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-06-11','08:00',120.00,10,19,3);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-07-11','16:00',110.00,10,17,1);
insert into consulta( data_consulta, hora_consulta, valor_consulta, Medico_id, Paciente_id, convenio_id)values('2015-08-11','10:00',120.00,10,26,2);
select * from consulta;
select * from receituario;
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 2 x ao dia entre 8 e 20 horas', 1);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('aldol', '1 ', 'Tomar 3 x ao dia, durante 7 dias', 3);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('AAS', '10 ', 'Tomar em caso de dor na cabeça', 3);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Fluoxetina ', '30', 'Tomar 1 x ao dia pela manhâ, durante um mês ao dia entre 8 e 20 horas', 5);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Ranitidina', '30', 'Tomar 1 x ao dia, para dores no estômago',7);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Loratadina', '28', 'Tomar 1 x ao dia, em caso de renite, se piorar voltar consulta', 10);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Prednisolona', '07', 'Tomar 1 x durante 7 dias', 13);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Nimesulida', '28', 'Tomar 3 x ao dia, durante 7 dias, em caso do dente doer mais, tomar junto o remédio AASS', 16);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Aciclovir ', '10', 'Tomar 1 x ao dia, indicado para Herpes Zoster', 19);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Diazepam', '28', 'Tomar 1 x ao dia', 20);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('Amitriptilina ', '10', 'Tomar 2 x ao dia entre 8 e 20 horas', 19);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',5);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',7);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',10);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',13);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',16);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',19);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',20);
insert into receituario (remedios, quantidade, instrucoes_uso, consulta_id)values('paracetamol', '10', 'Tomar 3 x ao dia de 8 em 8 horas, caso tenha dor ou febre',16);
select * from receituario;
